version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: url_postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: url_user
      POSTGRES_PASSWORD: url_pass
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: